name: Build & Publish

on:
  push:
    branches:
      - '**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: low-code-welding-frontend
  ORGANIZATION: ${{ github.repository_owner }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0

      - name: Lower-case organization name
        run: |
          echo "ORGANIZATION=${ORGANIZATION,,}" >>${GITHUB_ENV}
      - name: Log in to the Container registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.ORGANIZATION }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate version number
        id: semver
        uses: paulhatch/semantic-version@v4.0.2
        with:
          major_pattern: "/^MAJOR:.*$/"
          minor_pattern: "/^MINOR:.*$/"
          format: github.ref != 'refs/heads/main' && '${major}.${minor}.${patch}' || '${major}.${minor}.dev-${{ github.run_id }}'

      - name: Create GitHub release
        uses: actions/create-release@v1.1.4
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_IO_PAT }}
        with:
          tag_name: v${{ steps.semver.outputs.version }}
          release_name: Release v${{ steps.semver.outputs.version }}
          draft: false

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          push: true
          tags: "${{ env.REGISTRY }}/${{ env.ORGANIZATION }}/${{ env.IMAGE_NAME }}:${{ steps.semver.outputs.version }}"
